// <auto-generated />
using System;
using BigFourApp.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BigFourApp.Migrations
{
    [DbContext(typeof(BaseDatos))]
    partial class BaseDatosModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("BigFourApp.Models.Boleto", b =>
                {
                    b.Property<int>("Id_Boleto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Id_Asiento")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Id_DetalleVenta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Boleto");

                    b.HasIndex("Id_Asiento")
                        .IsUnique();

                    b.ToTable("Boletos");
                });

            modelBuilder.Entity("BigFourApp.Models.DetalleVenta", b =>
                {
                    b.Property<int>("Id_DetalleVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_Boleto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_Venta")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_DetalleVenta");

                    b.HasIndex("Id_Boleto")
                        .IsUnique();

                    b.HasIndex("Id_Venta");

                    b.ToTable("DetallesVenta");
                });

            modelBuilder.Entity("BigFourApp.Models.Event.Asiento", b =>
                {
                    b.Property<int>("Id_Asiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id_Asiento");

                    b.HasIndex("EventId");

                    b.ToTable("Asientos");
                });

            modelBuilder.Entity("BigFourApp.Models.Event.Classification", b =>
                {
                    b.Property<int>("Id_Classification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Segment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubGenre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Classification");

                    b.HasIndex("EventId");

                    b.ToTable("Classifications");
                });

            modelBuilder.Entity("BigFourApp.Models.Event.Evento", b =>
                {
                    b.Property<string>("Id_Evento")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SafeTix")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeatmapUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Evento");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("BigFourApp.Models.Event.Images", b =>
                {
                    b.Property<int>("Id_Image")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Image");

                    b.HasIndex("EventId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("BigFourApp.Models.Event.Venue", b =>
                {
                    b.Property<int>("Id_Venue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Venue");

                    b.HasIndex("EventId");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("BigFourApp.Models.Usuario", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ventaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id_Usuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BigFourApp.Models.Venta", b =>
                {
                    b.Property<int>("Id_Venta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Venta");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("BigFourApp.Models.Boleto", b =>
                {
                    b.HasOne("BigFourApp.Models.Event.Asiento", "Asiento")
                        .WithOne("Boleto")
                        .HasForeignKey("BigFourApp.Models.Boleto", "Id_Asiento")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Asiento");
                });

            modelBuilder.Entity("BigFourApp.Models.DetalleVenta", b =>
                {
                    b.HasOne("BigFourApp.Models.Boleto", "Boleto")
                        .WithOne("DetalleVenta")
                        .HasForeignKey("BigFourApp.Models.DetalleVenta", "Id_Boleto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BigFourApp.Models.Venta", "Venta")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("Id_Venta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Boleto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("BigFourApp.Models.Event.Asiento", b =>
                {
                    b.HasOne("BigFourApp.Models.Event.Evento", "Event")
                        .WithMany("Asientos")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Event");
                });

            modelBuilder.Entity("BigFourApp.Models.Event.Classification", b =>
                {
                    b.HasOne("BigFourApp.Models.Event.Evento", "Event")
                        .WithMany("Classifications")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("BigFourApp.Models.Event.Images", b =>
                {
                    b.HasOne("BigFourApp.Models.Event.Evento", "Event")
                        .WithMany("Images")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("BigFourApp.Models.Event.Venue", b =>
                {
                    b.HasOne("BigFourApp.Models.Event.Evento", "Event")
                        .WithMany("Venues")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Event");
                });

            modelBuilder.Entity("BigFourApp.Models.Venta", b =>
                {
                    b.HasOne("BigFourApp.Models.Usuario", "Usuario")
                        .WithMany("Ventas")
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BigFourApp.Models.Boleto", b =>
                {
                    b.Navigation("DetalleVenta");
                });

            modelBuilder.Entity("BigFourApp.Models.Event.Asiento", b =>
                {
                    b.Navigation("Boleto");
                });

            modelBuilder.Entity("BigFourApp.Models.Event.Evento", b =>
                {
                    b.Navigation("Asientos");

                    b.Navigation("Classifications");

                    b.Navigation("Images");

                    b.Navigation("Venues");
                });

            modelBuilder.Entity("BigFourApp.Models.Usuario", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("BigFourApp.Models.Venta", b =>
                {
                    b.Navigation("DetallesVenta");
                });
#pragma warning restore 612, 618
        }
    }
}
